### ISSUE TITLE
[Question] How can I adapt this code for VAEs with categorical latents?

### ISSUE THREAD

**Issue by roberthoenig** [bits-back/bits-back#2]
### My situation
I want to apply bits-back coding to a VAE with categorical latent variables. Specifically, each latent variable is distributed according to a categorical distribution with 256 possible values. The VAE in question is similar to the one in https://github.com/YongfeiYan/Gumbel_Softmax_VAE.

### My question
The repo features two examples of using bits-back coding to compress MNIST. For both examples, the VAE has latent variables that have an isotropic gaussian distribution. I'm now wondering what parts of the code I have to change in order to make bits-back coding work for latents with a categorical distribution. (With a prior that has a uniform categorical distribution.)

Looking at the code, it seems that I need to amend `post_pop` and `lik_append` in `vae_append`. The paper says that 
>The prior p(y) and the approximate posterior q(y | s) must share the same discretization.

However, since my latents have categorical distributions and are thus already discretized, is it possible to avoid this restriction?

If any of the above doesn't make sense, please feel free to ask for clarification :)

**Comment by tom-bird** [comment]
Hey - you are correct in saying that since your latents are discrete, you do not need to worry about discretization. The compression is simpler in the discrete case.

 Yes you do have to change the `post_pop` and `lik_append` in the `vae_append` function. The `vae_pop` function must also be changed (specifically the `lik_pop` and `post_append`) functions. The prior append and pop do not have to be altered since in the VAE we used there was a uniform prior, the same as your case.

We already have `categoricals_append` and `categoricals_pop` to perform coding with categorical distribution. If you are interested you can see their implementations [here](https://github.com/bits-back/bits-back/blob/cc8170950e2564670b85e06c770c837e57f6d35f/util.py#L237-L255).

I have mocked up the changes described below, disclaimer - I haven't actually run it but it should be OK. You will need to make sure your `gen_net` expects to get the latents in the set [0, 1, ..., 255] as inputs.

Let me know if you have more questions!

Another thing to note... we will soon be releasing a much faster, more flexible and user-friendly package to do lossless compression with ANS. Should hopefully make any other alterations to bits back and other compression schemes a lot simpler to implement :)

```
def cvae_append(latent_shape, gen_net, rec_net, obs_append, prior_prec=8,
               latent_prec=12):
    """
    VAE with discrete latents, parameterized by categorical dist and
    with uniform prior
    """
    def post_pop(data):
        posterior_probs = rec_net(data)
        return categoricals_pop(posterior_probs, latent_prec)

    def lik_append(latents):
        obs_params = gen_net(np.reshape(latents, latent_shape))
        return obs_append(obs_params)

    prior_append = uniforms_append(prior_prec)
    return bb_ans_append(post_pop, lik_append, prior_append)

def cvae_pop(
        latent_shape, gen_net, rec_net, obs_pop, prior_prec=8, latent_prec=12):
    """
    VAE with discrete latents, parameterized by categorical dist and
    with uniform prior
    """
    prior_pop = uniforms_pop(prior_prec, np.prod(latent_shape))

    def lik_pop(latents):
        obs_params = gen_net(np.reshape(latents, latent_shape))
        return obs_pop(obs_params)

    def post_append(data):
        posterior_probs = rec_net(data)
        return categoricals_append(posterior_probs, latent_prec)

    return bb_ans_pop(prior_pop, lik_pop, post_append)
```

**Comment by roberthoenig** [comment]
Thanks a ton @tom-bird ; I'll have to do a couple more tests before I'm confident in the results, but from what I can tell, the code you posted seems to work.

>Another thing to note... we will soon be releasing a much faster, more flexible and user-friendly package to do lossless compression with ANS. Should hopefully make any other alterations to bits back and other compression schemes a lot simpler to implement :)

Do you have an ETA for that package?

**Comment by roberthoenig** [comment]
(Closing this issue since https://github.com/bits-back/bits-back/issues/2#issuecomment-530786988 most likely resolves this. Will reopen in case I encounter problems in subsequent tests.)

**Comment by tom-bird** [comment]
> Do you have an ETA for that package?

We don't have a date, but most likely end of September/October

**Comment by tom-bird** [comment]
@roberthoenig FYI the new package is now availabe, find it [here](https://github.com/j-towns/craystack).

**Comment by roberthoenig** [comment]
Cool, thanks for the heads-up!
