### ISSUE TITLE
Appending integers to the stack

### ISSUE THREAD

**Issue by dsevero** [bits-back/bits-back#5]
Hi, @j-towns!

Quick question, if I want to append an integer between 1 and N to the stack, assuming a uniform distribution, is it possible to do with ceil(log2(N)) using your implementation? Or is there a minimum bit size to append to the stack?

I'm using [categorical_append](https://github.com/bits-back/bits-back/blob/7b03e2e21401a86d90c24d08962942236309a726/util.py#L237-L246) as 

```python
state = categorical_append(np.ones(N)/N, 8)(state, i)
```

where `i` is my integer. I'm not entirely sure about precision being `8`.

Thanks.

**Comment by j-towns** [comment]
Hey there! The easiest way to code uniform data is to use the [uniform append and pop functions](https://github.com/bits-back/bits-back/blob/7b03e2e21401a86d90c24d08962942236309a726/util.py#L20-L36). That allows you to append an integer symbol in the set `{0, 1, ..., 2 ** precision)` with a uniform distribution over those numbers. The precision can be as low as 1 (i.e. adding one uniformly distributed bit at a time).

When `precision` is close to 31 you will see a degredation in performance, this is because the stack precision, called r_t in my [ANS tutorial](https://arxiv.org/abs/2001.09186), and the other precision parameter r_s are implicitly set, in [rans.py](https://github.com/bits-back/bits-back/blob/7b03e2e21401a86d90c24d08962942236309a726/rans.py), to 32 and 63 respectively. As shown in the tutorial, we want the quantity r_s - r_t - `precision` == 31 - `precision` to be significantly greater than zero. I think we found that, in practice, for precision up to around 28 you don't get any noticable degredation in compression rate.

**Comment by dsevero** [comment]
Thank you!
